"""add_reset_token_to_profiles

Revision ID: fb9016b86fde
Revises: f8e7d6c5b4a3
Create Date: 2026-07-06 12:38:27.104705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb9016b86fde'
down_revision: Union[str, Sequence[str], None] = 'f8e7d6c5b4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_countries_name'), table_name='countries')
    op.create_unique_constraint(None, 'countries', ['name'])
    op.add_column('profiles', sa.Column('reset_token', sa.String(length=64), nullable=True))
    op.add_column('profiles', sa.Column('reset_token_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'reset_token_expires_at')
    op.drop_column('profiles', 'reset_token')
    op.drop_constraint(None, 'countries', type_='unique')
    op.create_index(op.f('uq_countries_name'), 'countries', ['name'], unique=True)
    # ### end Alembic commands ###
